name: Doc Builder
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./src/bot

jobs:
  BuildDoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: setup
      run: |
        npm ci
    - name: build
      run: |
        npm run build:doc
